name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip -q install --upgrade nbqa ruff yamllint
      - name: Run ruff on python files
        run: |
          python3 -m ruff check .
      - name: Run ruff on notebooks test files
        run: |
          python3 -m nbqa ruff .
      - name: Run yamllint
        run: |
          python3 -m yamllint -d "{extends: default, rules: {document-start: {present: false}, line-length: disable, truthy: {check-keys: false}}}" .
      - name: Check for stray outputs, counts and metadata in ipynb files
        uses: RBniCS/check-jupyter-metadata-action@main
        with:
          pattern: "**/*.ipynb"
