name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip3 -q install --upgrade flake8 Flake8-pyproject nbqa
      - name: Run flake8 checks
        run: |
          flake8 .
          nbqa flake8 .
      - name: Check for stray outputs, counts and metadata in ipynb files
        uses: RBniCS/check-jupyter-metadata-action@main
        with:
          pattern: "**/*.ipynb"
